name = 'Terminal2'
license = 'MPL-2.0'
licenselink = 'https://github.com/alvarocleite/terminal2-hugo-theme/blob/master/LICENSE'
description = 'Terminal2 is a fork or Terminal, a theme inspired by the cobalt 2 theme for terminal on macOS. It uses tailwind CSS to achieve the look and feel'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/alvarocleite/terminal2-hugo-theme'

# If you have a running demo of the theme
# TODO: Add a demo site
#demosite = 'https://nayanseth.com'

# Taxonomy terms
tags = ['blog', 'personal', 'responsive', 'terminal', 'dark mode', 'minimal', 'dark']
features = ['blog', 'personal', 'responsive', 'terminal', 'dark mode', 'minimal', 'dark', 'hugo', 'shortcodes', 'tailwind', 'markdown']

# If the theme has a single author
[author]
  name = 'Alvaro Castro Leite'
# TODO: Add personal site
#  homepage = 'https://nayanseth.com'